---
# Copyright 2016, JinkIT, and it's Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: placeholder for flannel
  debug: msg="starting flannel installation"

- name: ensure sdn bootstrap directory exists
  file: path=/etc/kubernetes/halcyon/network state=directory
  when: (kube_sdn_deploy == 'true')
  ignore_errors: true

- name: deploying flannel for kubernetes
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  register: deploy_flannel
  when: (kube_sdn == 'flannel')
  ignore_errors: true

- name: flannel deployment stdout
  debug: msg={{ deploy_flannel }}
  ignore_errors: true
